// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6U46_vpmQfV-V_ov-PBB30bBidz5R8ck',
    appId: '1:1041401962371:web:61a3a0d4ec6618502960b6',
    messagingSenderId: '1041401962371',
    projectId: 'studize-login',
    authDomain: 'studize-login.firebaseapp.com',
    storageBucket: 'studize-login.appspot.com',
    measurementId: 'G-YM5ZDTYC0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs0mRpsUZjV8_0EvbJbFmrE15gyEODO-g',
    appId: '1:1041401962371:android:1a0626eac48302812960b6',
    messagingSenderId: '1041401962371',
    projectId: 'studize-login',
    storageBucket: 'studize-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4IfRnR9YwrY6bWFtIovHU5ez4KXGNG64',
    appId: '1:1041401962371:ios:d0b1b8f37667d8072960b6',
    messagingSenderId: '1041401962371',
    projectId: 'studize-login',
    storageBucket: 'studize-login.appspot.com',
    androidClientId: '1041401962371-5do5m6mqbtr9g3srtelj6tsja1lvd63e.apps.googleusercontent.com',
    iosClientId: '1041401962371-jvlf9ko68cpc0vva6c2130336bq0vokp.apps.googleusercontent.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4IfRnR9YwrY6bWFtIovHU5ez4KXGNG64',
    appId: '1:1041401962371:ios:d0b1b8f37667d8072960b6',
    messagingSenderId: '1041401962371',
    projectId: 'studize-login',
    storageBucket: 'studize-login.appspot.com',
    androidClientId: '1041401962371-5do5m6mqbtr9g3srtelj6tsja1lvd63e.apps.googleusercontent.com',
    iosClientId: '1041401962371-jvlf9ko68cpc0vva6c2130336bq0vokp.apps.googleusercontent.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );
}
