// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9Eism_u_4PbUjO-AYohf8M7rAu8ZpCU',
    appId: '1:201442277639:web:2f853736d1a8358b07eda2',
    messagingSenderId: '201442277639',
    projectId: 'studize-firebase',
    authDomain: 'studize-firebase.firebaseapp.com',
    storageBucket: 'studize-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxW-pn8CmCId_LD3FjPBX_k1NWm0vylaI',
    appId: '1:201442277639:android:d396523e12e5ef3b07eda2',
    messagingSenderId: '201442277639',
    projectId: 'studize-firebase',
    storageBucket: 'studize-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkVteB_2rhUFtOAajrInQwQC9_C2fmEPE',
    appId: '1:201442277639:ios:9f66bc5abd912ad007eda2',
    messagingSenderId: '201442277639',
    projectId: 'studize-firebase',
    storageBucket: 'studize-firebase.appspot.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkVteB_2rhUFtOAajrInQwQC9_C2fmEPE',
    appId: '1:201442277639:ios:9f66bc5abd912ad007eda2',
    messagingSenderId: '201442277639',
    projectId: 'studize-firebase',
    storageBucket: 'studize-firebase.appspot.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );
}
