// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU79RS7wQXAI9iqtkby7PC-_2fV-4SJsk',
    appId: '1:101116459837:web:d998769f18183bbafde354',
    messagingSenderId: '101116459837',
    projectId: 'studizetest',
    authDomain: 'studizetest.firebaseapp.com',
    storageBucket: 'studizetest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOlYOt2JbxKRZK2VK3EkJtuGEZw7G8HQM',
    appId: '1:101116459837:android:3e3c6e798ea26210fde354',
    messagingSenderId: '101116459837',
    projectId: 'studizetest',
    storageBucket: 'studizetest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcajUQ9GJ2uZ5jbmvs-M3VhjZwJYbLRI',
    appId: '1:101116459837:ios:30be5b7e06dd0616fde354',
    messagingSenderId: '101116459837',
    projectId: 'studizetest',
    storageBucket: 'studizetest.appspot.com',
    androidClientId: '101116459837-gsnel6tv2kifv430p6emkol3l18b058b.apps.googleusercontent.com',
    iosClientId: '101116459837-1p6n8c1vba1o6usj8j38shcf60or4q69.apps.googleusercontent.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcajUQ9GJ2uZ5jbmvs-M3VhjZwJYbLRI',
    appId: '1:101116459837:ios:30be5b7e06dd0616fde354',
    messagingSenderId: '101116459837',
    projectId: 'studizetest',
    storageBucket: 'studizetest.appspot.com',
    androidClientId: '101116459837-gsnel6tv2kifv430p6emkol3l18b058b.apps.googleusercontent.com',
    iosClientId: '101116459837-1p6n8c1vba1o6usj8j38shcf60or4q69.apps.googleusercontent.com',
    iosBundleId: 'com.InnovAppWorks.studize',
  );
}
